server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # halaman reminder di /  dan isolir di /isolir.html
    location / {
        try_files $uri $uri/ =404;
    }

    # cache pendek biar update cepat kelihatan
    location ~* \.(html)$ {
        add_header Cache-Control "no-cache";
    }

    # jangan bocorkan versi nginx
    server_tokens off;
}
